# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'native' do
  # Use local pod when in development
  pod 'JZFlutter', :path => '../../'

  # if run in release mode(major, minor, patch) will not contain x86 architecture
  # pod 'JZFlutter', :git => 'https://github.com/JaminZhou/flutter-native-hybrid'
end
