# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'native' do
  #pod 'JZFlutter', :path => '../../'
  pod 'JZFlutter', :git => 'https://github.com/JaminZhou/JustTest'
end
