# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

flutter_application_path = '../../module/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)

target 'example' do
  
end
